### ISSUE TITLE
User Story 1: As a user, I want to be able to access resources showing me the effects of meditation, so that I can see how meditation can help with my stress.

### ISSUE THREAD

**Issue by goodtrailer** [cse110-team8-fa24/calmanaut#1]
### Sub-Tasks
* [x] cse110-team8-fa24/calmanaut#17
* [x] cse110-team8-fa24/calmanaut#18
* [x] cse110-team8-fa24/calmanaut#37

**Comment by DanielGalicia94** [comment]
Created the webpage, need to create tests to make sure
