### ISSUE TITLE
User Story 5: As a user, I would like to have my own account that I can use with my own progress tracker and other features that are personalized to me.

### ISSUE THREAD

**Issue by dmitrii-vikotorovich** [cse110-team8-fa24/calmanaut#2]
### Sub-Tasks
* [x] cse110-team8-fa24/calmanaut-server#1
* [x] cse110-team8-fa24/calmanaut#9
* [x] cse110-team8-fa24/calmanaut-server#2
* [x] cse110-team8-fa24/calmanaut-server#11

**Comment by goodtrailer** [comment]
All sub-tasks finished.

**Comment by goodtrailer** [comment]
Fixed by cse110-team8-fa24/calmanaut-server#19. It was an issue with backend cookie and proxy settings. Confirmed that it works on Chrome, Edge, Firefox, and Android Chrome: https://cse110-team8-fa24.github.io/calmanaut
