### ISSUE TITLE
User Story 2: As a user, I want sounds that evoke a sense of calm, such as music and ambient noises that will help get in the headspace for meditation.

### ISSUE THREAD

**Issue by goodtrailer** [cse110-team8-fa24/calmanaut#3]
### Sub-Tasks
* [x] cse110-team8-fa24/calmanaut#10
* [x] cse110-team8-fa24/calmanaut#14
* [x] cse110-team8-fa24/calmanaut#34

**Comment by Firecrafter703** [comment]
Webpage can play music, buts its an html page, not a tsx. I need to ensure that npm start works in my computer before I can continue.

**Comment by goodtrailer** [comment]
All subtasks completed.
