### ISSUE TITLE
User Story 3: As a user, I want calming visuals, based on nature themes, soothing colors, and timing such that I can focus on my meditation and achieve a sense of relaxation.

### ISSUE THREAD

**Issue by goodtrailer** [cse110-team8-fa24/calmanaut#4]
### Sub-Tasks
* [x] cse110-team8-fa24/calmanaut#11
* [x] cse110-team8-fa24/calmanaut#13
* [x] cse110-team8-fa24/calmanaut#36

**Comment by dmitrii-vikotorovich** [comment]
Completed User Story 3
