### ISSUE TITLE
User Story 4: As a user, I would like to have a progress tracker with daily/weekly/monthly streaks and reminders so that I can maintain consistency in my meditation practice and be reminded if I am falling out of track.

### ISSUE THREAD

**Issue by goodtrailer** [cse110-team8-fa24/calmanaut#6]
### Sub-Tasks
* [x] cse110-team8-fa24/calmanaut-server#5
* [x] cse110-team8-fa24/calmanaut-server#7
* [x] cse110-team8-fa24/calmanaut-server#12
* [x] cse110-team8-fa24/calmanaut#26
* [x] cse110-team8-fa24/calmanaut#21
* [x] cse110-team8-fa24/calmanaut#23

**Comment by goodtrailer** [comment]
All subtasks closed.
