### ISSUE TITLE
User Story 6: As a user, I’d love to have a personalized space on the website. Everyone finds relaxation in their own way, and having a customized area would make the experience feel more comfortable and personal.

### ISSUE THREAD

**Issue by goodtrailer** [cse110-team8-fa24/calmanaut#7]
### Sub-Tasks 
* [ ] cse110-team8-fa24/calmanaut#27
* [ ] cse110-team8-fa24/calmanaut#30
* [x] cse110-team8-fa24/calmanaut-server#20
* [ ] cse110-team8-fa24/calmanaut#32
* [x] cse110-team8-fa24/calmanaut#33
* [x] cse110-team8-fa24/calmanaut-server#10

**Comment by sriyaa1504** [comment]
### Sub-Tasks 
* [ ] cse110-team8-fa24/calmanaut#27

**Comment by sriyaa1504** [comment]
### Sub-Tasks
* [ ] cse110-team8-fa24/calmanaut#30
