### ISSUE TITLE
User Story 8:  As a user, I want to connect with my friends such that we can share our progress, support each other, and create a sense of community around our meditation practice.

### ISSUE THREAD

**Issue by goodtrailer** [cse110-team8-fa24/calmanaut#8]
### Sub-Tasks:
* [ ] cse110-team8-fa24/calmanaut#20
* [ ] cse110-team8-fa24/calmanaut-server#8
* [ ] cse110-team8-fa24/calmanaut-server#9
